PCbuild(ASP.MVC)/Controllers/CompareController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PCbuilder_ASP.MVC_.Services.Comparison;
using PCbuilder_ASP.MVC_.Domain.Abstract;
using PCbuilder_ASP.MVC_.Models;
using PCbuilder_ASP.MVC_.Models.ViewModel;
using PCbuilder_ASP.MVC_.Services.Interfaces;
using PCbuilder_ASP.MVC_.Services.DTO;
using AutoMapper;

namespace PCbuilder_ASP.MVC_.Controllers
{
    public class CompareController : Controller
    {
        ICompareService Service;
        IMapper Mapper;

        public CompareController(ICompareService compareService, IMapper mapper)
        {
            Service = compareService;
            Mapper = mapper;
        }

        // GET: Compare
        public ActionResult Index(string returnUrl)
        {
            return View(returnUrl);
        }

        public ActionResult CPUCompare(
            Comparison<CPUViewModel> comparison,
            string returnUrl)
        {
            return View(new CompareIndexViewModel<CPUViewModel>
            {
                Comparison = comparison,
                returnUrl = returnUrl
            });
        }

        [HttpPost]
        public RedirectToRouteResult CPUAddToCompare(
            Comparison<CPUViewModel> comparison, 
            System.Guid ProductGuid, 
            string returnUrl)
        {
            CPUdto cpudto = Service.FindCPUByID(ProductGuid);
            var cpu = Mapper.Map<CPUdto, CPUViewModel>(cpudto);
            if (cpu != null)
            {
                comparison.AddItem(cpu);
            }
            return RedirectToAction("CPUCompare", new { returnUrl });
        }

        [HttpPost]
        public RedirectToRouteResult CPURemoveFromCompare(
            Comparison<CPUViewModel> comparison, 
            System.Guid ProductGuid, 
            string returnUrl)
        {
            CPUdto cpudto = Service.FindCPUByID(ProductGuid);
            CPUViewModel cpu = Mapper.Map<CPUdto,CPUViewModel>(cpudto);
            if (cpu != null)
            {
                comparison.Remove(cpu);
            }
            return RedirectToAction("CPUCompare", new { returnUrl });
        }

        [HttpPost]
        public RedirectToRouteResult CPUClearCompare(
            Comparison<CPUViewModel> comparison, 
            string returnUrl)
        {
            comparison.Clear();
            return RedirectToAction("CPUCompare", new { returnUrl });
        }

        public ActionResult GPUCompare(
            Comparison<GPUViewModel> comparison, 
            string returnUrl)
        {
            return View(new CompareIndexViewModel<GPUViewModel>
            {
                Comparison = comparison,
                returnUrl = returnUrl
            });
        }

        [HttpPost]
        public RedirectToRouteResult GPUAddToCompare(
            Comparison<GPUViewModel> comparison, 
            System.Guid ProductGuid, 
            string returnUrl)
        {
            GPUdto gpudto = Service.FindGPUByID(ProductGuid);
            GPUViewModel gpu = Mapper.Map<GPUdto,GPUViewModel>(gpudto);
            if (gpu != null)
            {
                comparison.AddItem(gpu);
            }
            return RedirectToAction("GPUCompare", new { returnUrl });
        }

        [HttpPost]
        public RedirectToRouteResult GPURemoveFromCompare(
            Comparison<GPUViewModel> comparison, 
            System.Guid ProductGuid, 
            string returnUrl)
        {
            GPUdto gpudto = Service.FindGPUByID(ProductGuid);
            GPUViewModel gpu = Mapper.Map<GPUdto, GPUViewModel>(gpudto);
            if (gpu != null)
            {
                comparison.Remove(gpu);
            }
            return RedirectToAction("GPUCompare", new { returnUrl });
        }

        [HttpPost]
        public RedirectToRouteResult GPUClearCompare(
            Comparison<GPUViewModel> comparison, 
            string returnUrl)
        {
            comparison.Clear();
            return RedirectToAction("GPUCompare", new { returnUrl });
        }
    }
}

PCbuild(ASP.MVC)/Controllers/ShowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PCbuilder_ASP.MVC_.Domain.Abstract;
using PCbuilder_ASP.MVC_.Models;
using PCbuilder_ASP.MVC_.Services.DTO;
using PCbuilder_ASP.MVC_.Services.Interfaces;

namespace PCbuilder_ASP.MVC_.Controllers
{
    public class ShowController : AsyncController
    {
        IShowService Service;
        IMapper Mapper;
        public int PageSize = 10;

        ICPURepository CPURepository;
        IGPURepository GPURepository;
        IGameRepository gameRepository;

        public ShowController(
            ICPURepository cPU, 
            IGPURepository gPU, 
            IGameRepository game, 
            IShowService service,
            IMapper mapper)
        {
            Service = service;
            Mapper = mapper;
            CPURepository = cPU;
            GPURepository = gPU;
            gameRepository = game;
        }

        // GET: Show
        public ViewResult ListCPU(int page=1)
        {
            var cpuListDTO = Service.ListCPU(page);
            var cpuList = Mapper.Map<CPUListDTO, CPUListViewModel>(cpuListDTO);

            
            return View(cpuList);
        }

        public ViewResult ListGPU(int page = 1)
        {
            var gpuListDTO = Service.ListGPU(page);
            var gpuList = Mapper.Map<GPUListDTO, GPUListViewModel>(gpuListDTO);

            return View(gpuList);
        }

        public ViewResult ListGame(int page = 1)
        {
            var gameListDTO = Service.ListGame(page);
            var gameList = Mapper.Map<GameListDTO, GameListViewModel>(gameListDTO);

            return View(gameList);
        }
    }
}

PCbuild(ASP.MVC)/Views/Shared/CPUSummary.cshtml
@model PCbuilder_ASP.MVC_.Models.ViewModel.CPUViewModel

<div class="item">
    <h3>@Model.Manufacture @Model.ProcessorNumber</h3>
    <p>Number Of Cores: @Model.NumberOfCores</p>
    <p>Number Of Threads: @Model.NumberOfThreads</p>
    <p>PBF: @Model.PBF</p>
    @using (Html.BeginForm("CPUAddToCompare", "Compare"))
    {
        @Html.HiddenFor(x=>x.ProductGuid)
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
        <input type="submit" value="Add to compare" class="btn btn-primary"/>
    }
</div>

PCbuild(ASP.MVC)/Views/Shared/GPUSummary.cshtml
@model PCbuilder_ASP.MVC_.Models.ViewModel.GPUViewModel

<div class="item">
    <h3>@Model.Manufacture @Model.Name</h3>
    <p>Memory speed: @Model.MemorySpeed</p>
    <p>Boost Clock: @Model.BoostClock</p>
    <p>AverageBench: @Model.AverageBench</p>
    @using (Html.BeginForm("GPUAddToCompare", "Compare"))
    {
        @Html.HiddenFor(x=>x.ProductGuid)
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
        <input type="submit" value="Add to compare" class="btn btn-primary"/>
    }
</div>

PCbuild(ASP.MVC)/Views/Shared/GameSummary.cshtml
@model PCbuilder_ASP.MVC_.Models.ViewModel.GameViewModel

<div class="item">
    <h3>@Model.Name</h3>
    @if (@Model.ImageData64 != null || @Model.ImageData32 != null)
    {
        <img src="@Url.Action("GetImage", "Build", new { Model.GameGuid})" />
    }
</div>

PCbuild(ASP.MVC)/Views/Shared/ShowMenu.cshtml
@model string

@*<script language="javascript">
</script>
<script>
    var UL = document.getElementById("smenu");
    UL.children.forEach(function (item, i, UL) {
        var ch = item.firstChild;
        if (id =="@Model") {
            item.classList.add("active");
        }
    });
</script>*@

<ul id="smenu" class="nav nav-pills">
    <li
        @{ 
            var cpu = "";
            if (@Model == "CPU")
            {
                cpu = "active";
            }
        }
         class = @cpu 
            
        >@Html.ActionLink("CPU","ListCPU", "Show", new { @id="CPU" })</li>
    <li
        @{ 
            var gpu = "";
            if (@Model == "GPU")
            {
                gpu = "active";
            }
        }
         class = @gpu
        >@Html.ActionLink("GPU","ListGPU","Show", new { @id="GPU" })</li>
    <li
        @{ 
            var game = "";
            if (@Model == "Game")
            {
                game = "active";
            }
        }
         class = @game
        >@Html.ActionLink("Game","ListGame","Show", new { @id ="Game" })</li>
</ul>

PCbuild(ASP.MVC)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PC Build App", "Index", "Build", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Build", "Index", "Build")</li>
                    <li>@Html.ActionLink("Products", "ListCPU", "Show")</li>
                    <li>@Html.ActionLink("Compare", "Index", "Compare")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-info alert-dismissable fade in" role="alert">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    @TempData["message"]
                </div>
            }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Application.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>