PCbuild(ASP.MVC)/Models/ViewModel/GameViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PCbuilder_ASP.MVC_.Models.ViewModel
{
    public class GameViewModel
    {
        public Guid GameGuid { get; set; }

        public string Name { get; set; }

        public int AverangeRequirements { get; set; }

        public byte[] ImageData32 { get; set; }

        public string ImageMimeType32 { get; set; }

        public byte[] ImageData64 { get; set; }

        public string ImageMimeType64 { get; set; }
    }
}

PCbuild(ASP.MVC)/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PCbuilder_ASP.MVC_.Domain.Abstract;
using PCbuilder_ASP.MVC_.Domain.Entities;
using System.Drawing;
using PCbuilder_ASP.MVC_.Services.Interfaces;
using AutoMapper;
using PCbuilder_ASP.MVC_.Models.ViewModel;
using PCbuilder_ASP.MVC_.Services.DTO;

namespace PCbuilder_ASP.MVC_.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GamesController : Controller
    {
        IGameService Service;
        IMapper Mapper;

        public GamesController(IGameService service, IMapper mapper)
        {
            Service = service;
            Mapper = mapper;
        }

        // GET: Games
        public ActionResult Index()
        {
            var gamesdto = Service.GetGames();
            var games =
                Mapper.Map<IEnumerable<GameDTO>, IEnumerable<GameViewModel>>(gamesdto);
            return View(games);
        }

        public ViewResult Edit(Guid GameGuid)
        {
            GameDTO gamedto = Service.GetGameByID(GameGuid);
            var game = Mapper.Map<GameDTO, GameViewModel>(gamedto);
            return View(game);
        }

        [HttpPost]
        public ActionResult Edit(GameViewModel game, HttpPostedFileBase Image32, HttpPostedFileBase Image64)
        {
            if (ModelState.IsValid)
            {
                if (Image32 != null)
                {
                    game.ImageMimeType32 = Image32.ContentType;
                    game.ImageData32 = new byte[Image32.ContentLength];
                    Image32.InputStream.Read(game.ImageData32, 0, Image32.ContentLength);
                }
                if (Image64 != null)
                {
                    game.ImageMimeType64 = Image64.ContentType;
                    game.ImageData64 = new byte[Image64.ContentLength];
                    Image64.InputStream.Read(game.ImageData64, 0, Image64.ContentLength);
                }
                var gamedto = Mapper.Map<GameViewModel, GameDTO>(game);
                Service.EditGame(gamedto);

                TempData["message"] =
                    string.Format("{0} has been saved", game.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(game);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new GameViewModel());
        }

        public ActionResult Create(GameViewModel game)
        {
            if (ModelState.IsValid)
            {
                var gamedto = Mapper.Map<GameViewModel, GameDTO>(game);
                Service.SaveGame(gamedto);

                TempData["message"] =
                    string.Format("{0} has been created", game.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(game);
            }
        }

        [HttpDelete]
        public ActionResult Delete(Guid GameID)
        {
            GameDTO deletedGame = Service.GetGameByID(GameID);
            Service.DeleteGame(GameID);
            if (deletedGame != null)
            {
                TempData["message"] = string.Format("{0} was deleted", deletedGame.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

PCbuild(ASP.MVC)/Views/Games/Edit.cshtml
@model PCbuilder_ASP.MVC_.Models.ViewModel.GameViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Games", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x => x.GameGuid);
    <div class="ro">Name:</div><div> @Html.EditorFor(x => x.Name);</div>
    <div>AverangeRequirements:</div><div> @Html.EditorFor(x => x.AverangeRequirements);</div>
    <div>Image(low)</div>
    <div>
        @if (Model.ImageData32 == null)
        {
            @:None
        }
        else
        {
            <img src="@Url.Action("GetImage", "Build", new {Model.GameGuid, big=false })" />
        }
    </div>
    <label class="btn btn-primary">
        Upload new image:
        <input type="file" name="Image32" hidden/>
    </label>
    <div>Image(high)</div>
    <div>
        @if (Model.ImageData64 == null)
        {
            @:None
        }
        else
        {
            <img src="@Url.Action("GetImage", "Build", new { Model.GameGuid, big=true })" />
        }
    </div>
    <label class="btn btn-primary">
        Upload new image:
        <input type="file" name="Image64" hidden/>
    </label>
    <input type="submit" value="Save" class="btn btn-primary" />
    @Html.ActionLink("Back", "Index");
}

PCbuild(ASP.MVC)/Views/Games/Index.cshtml
@model IEnumerable<PCbuilder_ASP.MVC_.Models.ViewModel.GameViewModel>

@{
    ViewBag.Title = "Games";
}

<h2>Games</h2>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Actions</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.GameGuid</td>
            <td>@Html.ActionLink(item.Name, "Edit", new { item.GameGuid })</td>
            <td>
                @using (Html.BeginForm("Delete", "Games"))
                {
                    @Html.Hidden("GameID", item.GameGuid)
                    <input type="submit" value="Delete" class="btn btn-danger"/>
                }
            </td>
        </tr>
    }
</table>
<p>@Html.ActionLink("Add a new product", "Create")</p>