PCbuild(ASP.MVC)/Models/ViewModel/GPUViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PCbuilder_ASP.MVC_.Models.ViewModel
{
    public class GPUViewModel
    {
        public Guid ProductGuid { get; set; }

        public string Status { get; set; }

        public string Manufacture { get; set; }

        public string Developer { get; set; }

        public string Name { get; set; }

        public string Architecture { get; set; }

        public int BoostClock { get; set; }

        public int FrameBuffer { get; set; }

        public int MemorySpeed { get; set; }

        public int AverageBench { get; set; }

        public virtual PriceViewModel Price { get; set; }

        public override bool Equals(object obj)
        {
            if ((obj == null) || !this.GetType().Equals(obj.GetType()))
            {
                return false;
            }
            else
            {
                GPUViewModel gpu = (GPUViewModel)obj;
                return (this.ProductGuid == gpu.ProductGuid);
            }
        }

        public override int GetHashCode()
        {
            return ProductGuid.GetHashCode();
        }
    }
}

PCbuild(ASP.MVC)/Controllers/GPUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PCbuilder_ASP.MVC_.Domain.Abstract;
using PCbuilder_ASP.MVC_.Domain.Entities;
using PCbuilder_ASP.MVC_.Models.ViewModel;
using PCbuilder_ASP.MVC_.Services.DTO;
using PCbuilder_ASP.MVC_.Services.Interfaces;

namespace PCbuilder_ASP.MVC_.Controllers
{
    //[Authorize(Roles ="Admin")]
    public class GPUsController : Controller
    {
        IGPUService Service;
        IMapper Mapper;

        public GPUsController(IGPUService service, IMapper mapper)
        {
            Service = service;
            Mapper = mapper;
        }

        // GET: GPUs
        public ActionResult Index()
        {
            var gpus = Mapper.Map<IEnumerable<GPUdto>, IEnumerable<GPUViewModel>>(Service.GetGPUs());
            return View(gpus);
        }


        public ViewResult Edit(Guid id)
        {
            var gpu = Mapper.Map<GPUdto, GPUViewModel>(Service.GetGPUByID(id));
            return View(gpu);
        }

        [HttpPost]
        public ActionResult Edit(GPUViewModel gpu)
        {
            if (ModelState.IsValid)
            {
                var gpudto = Mapper.Map<GPUViewModel, GPUdto>(gpu);
                Service.EditGPU(gpudto);
                TempData["message"] = string.Format("{0} has been saved", gpu.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(gpu);
            }
        }

        public ActionResult Create(GPUViewModel gpu)
        {
            if (ModelState.IsValid)
            {
                var gpudto = Mapper.Map<GPUViewModel, GPUdto>(gpu);
                Service.SaveGPU(gpudto);
                return RedirectToAction("Index");
            }

            return View(gpu);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            var deletedGPU = Service.GetGPUByID(id);
            Service.DeleteGPU(id);
            if (deletedGPU != null)
            {
                TempData["message"] = string.Format("{0} was deleted", deletedGPU.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

PCbuild(ASP.MVC)/Views/GPUs/Create.cshtml
@model PCbuilder_ASP.MVC_.Models.ViewModel.GPUViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Edit</h2>

@using (Html.BeginForm("Create", "GPUs", FormMethod.Post))
{
    <div class="form-horizontal">


        @Html.HiddenFor(x => x.ProductGuid)
        <div class="form-group">
            @Html.LabelFor(x => x.Manufacture, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(x => x.Manufacture)
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(x => x.Name, new { @class = " col-md-10 form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Architecture, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(x => x.Architecture, new { @class = " col-md-10 form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.BoostClock, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(x => x.BoostClock, new { @class = " col-md-10 form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.FrameBuffer, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(x => x.FrameBuffer, new { @class = " col-md-10 form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.MemorySpeed, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(x => x.MemorySpeed, new { @class = "col-md-10 form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.AverageBench, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(x => x.AverageBench, new { @class = " col-md-10 form-control" })
        </div>
        @*<div class="form-group"> @Html.EditorFor(x => x.prices.FirstOrDefault().Amount)</div>*@
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}
@Html.ActionLink("Back", "Index")

PCbuild(ASP.MVC)/Views/GPUs/Edit.cshtml
@model PCbuilder_ASP.MVC_.Models.ViewModel.GPUViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "GPUs", FormMethod.Post))
{
<div class="form-horizontal">


    @Html.HiddenFor(x => x.ProductGuid)
    <div class="form-group">
        @Html.LabelFor(x => x.Manufacture, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(x => x.Manufacture)
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(x => x.Name, new { @class = " col-md-10 form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Architecture, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(x => x.Architecture, new { @class = " col-md-10 form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.BoostClock, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(x => x.BoostClock, new { @class = " col-md-10 form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.FrameBuffer, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(x => x.FrameBuffer, new { @class = " col-md-10 form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.MemorySpeed, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(x => x.MemorySpeed, new { @class = "col-md-10 form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.AverageBench, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.EditorFor(x => x.AverageBench, new { @class = " col-md-10 form-control" })
    </div>
    @*<div class="form-group"> @Html.EditorFor(x => x.prices.FirstOrDefault().Amount)</div>*@
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-default" />
    </div>
</div>
    }
    @Html.ActionLink("Back", "Index")

PCbuild(ASP.MVC)/Views/GPUs/Index.cshtml
@model IEnumerable<PCbuilder_ASP.MVC_.Models.ViewModel.GPUViewModel>

@{
    ViewBag.Title = "GPUs";
}

<h2>GPUs</h2>


<p>@Html.ActionLink("Create New","Create")</p>
<table class="table">

    <tr>
        <th>@Html.DisplayNameFor(Model=>Model.Manufacture)</th>
        <th>@Html.DisplayNameFor(Model => Model.Name)</th>
        <th>@Html.DisplayNameFor(Model => Model.Architecture)</th>
        <th>@Html.DisplayNameFor(Model => Model.BoostClock)</th>
        <th>@Html.DisplayNameFor(Model => Model.FrameBuffer)</th>
        <th>@Html.DisplayNameFor(Model => Model.MemorySpeed)</th>
        <th>@Html.DisplayNameFor(Model => Model.AverageBench)</th>
        @*<th>@Html.DisplayNameFor(Model => Model.PriceGPUs)</th>*@
        <th></th>
    </tr>
    @foreach(var item in Model)
    {
    <tr>
        <td>@Html.DisplayFor(ItemModel => item.Manufacture)</td>
        <td>@Html.DisplayFor(ItemModel => item.Name)</td>
        <td>@Html.DisplayFor(ItemModel => item.Architecture)</td>
        <td>@Html.DisplayFor(ItemModel => item.BoostClock)</td>
        <td>@Html.DisplayFor(ItemModel => item.FrameBuffer)</td>
        <td>@Html.DisplayFor(ItemModel => item.MemorySpeed)</td>
        <td>@Html.DisplayFor(ItemModel => item.AverageBench)</td>
        @*<td>@Html.DisplayFor(ItemModel=> item.prices.FirstOrDefault().Amount.ToString())</td>*@
        <td>
            @Html.ActionLink("Edit","Edit", new { id=item.ProductGuid}) |
            @Html.ActionLink("Delete","Delete", new { id=item.ProductGuid})
        </td>
    </tr>
    }
</table>